parameters:
    sidus_eav_model.form.type.data.class: Sidus\EAVModelBundle\Form\DataType
    sidus_eav_model.form.type.simple_data_selector.class: Sidus\EAVModelBundle\Form\SimpleDataSelectorType
    sidus_eav_model.form.type.autocomplete_data_selector.class: Sidus\EAVModelBundle\Form\AutocompleteDataSelectorType
    sidus_eav_model.form.type.bootstrap_collection.class: Sidus\EAVModelBundle\Form\BootstrapCollectionType

services:
    sidus_eav_model.form.type.data:
        class: %sidus_eav_model.form.type.data.class%
        arguments: [%sidus_eav_model.entity.data.class%]
        calls:
            - [setFamilyConfiguration, [@sidus_eav_model.family_configuration.handler]]
            - [setTranslator, [@translator]]
        tags:
            - { name: form.type, alias: sidus_data }

    sidus_eav_model.form.type.simple_data_selector:
        class: %sidus_eav_model.form.type.simple_data_selector.class%
        arguments: [%sidus_eav_model.entity.data.class%]
        tags:
            - { name: form.type, alias: sidus_simple_data_selector }

    sidus_eav_model.form.type.autocomplete_data_selector:
        class: %sidus_eav_model.form.type.autocomplete_data_selector.class%
        arguments: [%sidus_eav_model.entity.data.class%, @sidus_eav_model.doctrine.repository.data, @sidus_eav_model.family_configuration.handler]
        tags:
            - { name: form.type, alias: sidus_autocomplete_data_selector }

    sidus_eav_model.form.type.bootstrap_collection:
        class: %sidus_eav_model.form.type.bootstrap_collection.class%
        tags:
            - { name: form.type, alias: bootstrap_collection }
