parameters:
    sidus_eav_model.form.type.data.class: Sidus\EAVModelBundle\Form\Type\DataType
    sidus_eav_model.form.type.simple_data_selector.class: Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType

services:
    sidus_eav_model.form.type.data:
        class: %sidus_eav_model.form.type.data.class%
        arguments: [%sidus_eav_model.entity.data.class%, %sidus_eav_model.form.collection_type%]
        calls:
            - [setFamilyConfiguration, [@sidus_eav_model.family_configuration.handler]]
            - [setTranslator, [@translator]]
        tags:
            - { name: form.type, alias: sidus_data }

    sidus_eav_model.form.type.simple_data_selector:
        class: %sidus_eav_model.form.type.simple_data_selector.class%
        arguments: [%sidus_eav_model.entity.data.class%]
        tags:
            - { name: form.type, alias: sidus_simple_data_selector }
