parameters:
    sidus_eav_model.attribute.class: Sidus\EAVModelBundle\Model\Attribute
    sidus_eav_model.family.class: Sidus\EAVModelBundle\Model\Family
    sidus_eav_model.attribute_type_configuration.handler.class: Sidus\EAVModelBundle\Configuration\AttributeTypeConfigurationHandler
    sidus_eav_model.attribute_configuration.handler.class: Sidus\EAVModelBundle\Configuration\AttributeConfigurationHandler
    sidus_eav_model.family_configuration.handler.class: Sidus\EAVModelBundle\Configuration\FamilyConfigurationHandler
    sidus_eav_model.event.data_event_subscriber.class: Sidus\EAVModelBundle\Event\DataEventSubscriber
    sidus_eav_model.doctrine.repository.data.class: Sidus\EAVModelBundle\Entity\DataRepository
    sidus_eav_model.exception.handler.class: Sidus\EAVModelBundle\Event\ExceptionListener
    sidus_eav_model.validator.sidus_data.class: Sidus\EAVModelBundle\Validator\Constraints\DataValidator

services:
    sidus_eav_model.attribute_type_configuration.handler:
        class: %sidus_eav_model.attribute_type_configuration.handler.class%

    sidus_eav_model.attribute_configuration.handler:
        class: %sidus_eav_model.attribute_configuration.handler.class%

    sidus_eav_model.family_configuration.handler:
        class: %sidus_eav_model.family_configuration.handler.class%

    sidus_eav_model.event.data_event_subscriber:
        class: %sidus_eav_model.event.data_event_subscriber.class%
        arguments: [ @sidus_eav_model.family_configuration.handler ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    sidus_eav_model.doctrine.repository.data:
        class: %sidus_eav_model.doctrine.repository.data.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [%sidus_eav_model.entity.data.class%]

    sidus_eav_model.exception.handler:
        class: %sidus_eav_model.exception.handler.class%
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_subscriber }

    sidus_eav_model.validator.sidus_data:
        class: %sidus_eav_model.validator.sidus_data.class%
        arguments: [%sidus_eav_model.entity.data.class%, @sidus_eav_model.family_configuration.handler, @translator, @doctrine]
        tags:
            - { name: validator.constraint_validator, alias: sidus_data }
