services:
    Sidus\EAVModelBundle\Cache\AnnotationGenerator:
        class: Sidus\EAVModelBundle\Cache\AnnotationGenerator
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@doctrine.orm.entity_manager'
            - '%kernel.root_dir%/../var'
        tags:
            - { name: kernel.cache_warmer, priority: 0 }
