services:
    sidus_eav_model.attribute_type.registry:
        class: Sidus\EAVModelBundle\Registry\AttributeTypeRegistry

    sidus_eav_model.attribute.registry:
        class: Sidus\EAVModelBundle\Registry\AttributeRegistry
        arguments:
            - '%sidus_eav_model.attribute.class%'
            - '%sidus_eav_model.context.global_mask%'
            - '@sidus_eav_model.attribute_type.registry'
            - '@translator'

    sidus_eav_model.family.registry:
        class: Sidus\EAVModelBundle\Registry\FamilyRegistry
        tags:
            - { name: doctrine.event_listener, event: sidus_family_configuration }
