services:
    Sidus\EAVModelBundle\Registry\AttributeTypeRegistry:
        class: Sidus\EAVModelBundle\Registry\AttributeTypeRegistry

    Sidus\EAVModelBundle\Registry\AttributeRegistry:
        class: Sidus\EAVModelBundle\Registry\AttributeRegistry
        arguments:
            - '%sidus_eav_model.attribute.class%'
            - '%sidus_eav_model.context.global_mask%'
            - '@Sidus\EAVModelBundle\Registry\AttributeTypeRegistry'
            - '@translator'

    Sidus\EAVModelBundle\Registry\FamilyRegistry:
        class: Sidus\EAVModelBundle\Registry\FamilyRegistry
        arguments:
            - '@annotations.reader'
        tags:
            - { name: doctrine.event_listener, event: sidus_family_configuration }
