services:
    Sidus\EAVModelBundle\Context\ContextManagerInterface:
        alias: Sidus\EAVModelBundle\Context\ContextManager

    Sidus\EAVModelBundle\Context\ContextManager:
        class: Sidus\EAVModelBundle\Context\ContextManager
        arguments:
            - '@form.factory'
            - '@logger'
            - '%sidus_eav_model.context.form_type%'
            - '%sidus_eav_model.context.default_context%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: 10 }
