parameters:
    sidus_eav_model.datagrid.renderer.choice_types:
        - choice

services:
    # Datagrid bundle v1.*
    Sidus\EAVModelBundle\DataGrid\DataRenderer:
        class: Sidus\EAVModelBundle\DataGrid\DataRenderer
        decorates: Sidus\DataGridBundle\Renderer\RenderableInterface
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\DataGrid\DataRenderer.inner'
            - '@translator'
            - '%sidus_eav_model.datagrid.renderer.choice_types%'

    Sidus\EAVModelBundle\DataGrid\EAVColumnRenderer:
        class: Sidus\EAVModelBundle\DataGrid\EAVColumnRenderer
        decorates: Sidus\DataGridBundle\Renderer\ColumnRendererInterface
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\DataGrid\EAVColumnRenderer.inner'
            - '@translator'
