services:
    sidus_eav_model.attribute_type.registry:
        alias: Sidus\EAVModelBundle\Registry\AttributeTypeRegistry

    sidus_eav_model.attribute.registry:
        alias: Sidus\EAVModelBundle\Registry\AttributeRegistry

    sidus_eav_model.family.registry:
        alias: Sidus\EAVModelBundle\Registry\FamilyRegistry

    sidus_eav_model.context.manager:
        alias: Sidus\EAVModelBundle\Context\ContextManagerInterface

    sidus_eav_model.finder:
        alias: Sidus\EAVModelBundle\Doctrine\EAVFinder

    sidus_eav_model.entity.data_loader:
        alias: Sidus\EAVModelBundle\Doctrine\DataLoaderInterface

    sidus_eav_model.form.attribute_builder:
        alias: Sidus\EAVModelBundle\Form\AttributeFormBuilderInterface

    sidus_eav_model.form.type.data:
        alias: Sidus\EAVModelBundle\Form\Type\DataType

    sidus_eav_model.manager.data:
        alias: Sidus\EAVModelBundle\Manager\DataManager
