services:
    sidus_eav_model.denormalizer.data:
        alias: Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer

    sidus_eav_model.denormalizer.family:
        alias: Sidus\EAVModelBundle\Serializer\Denormalizer\FamilyDenormalizer

    sidus_eav_model.normalizer.data:
        alias: Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer

    sidus_eav_model.normalizer.family:
        alias: Sidus\EAVModelBundle\Serializer\Normalizer\FamilyNormalizer

    sidus_eav_model.normalizer.attribute:
        alias: Sidus\EAVModelBundle\Serializer\Normalizer\AttributeNormalizer

    sidus_eav_model.serializer.handler.max_depth:
        alias: Sidus\EAVModelBundle\Serializer\MaxDepthHandler

    sidus_eav_model.serializer.handler.circular_reference:
        alias: Sidus\EAVModelBundle\Serializer\CircularReferenceHandler

    sidus_eav_model.serializer.handler.by_reference:
        alias: Sidus\EAVModelBundle\Serializer\ByReferenceHandler

    sidus_eav_model.serializer.entity_provider:
        alias: Sidus\EAVModelBundle\Serializer\EntityProviderInterface
