services:
    Sidus\EAVModelBundle\Doctrine\EAVFinder:
        class: Sidus\EAVModelBundle\Doctrine\EAVFinder
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '@Sidus\EAVModelBundle\Doctrine\DataLoaderInterface'

    Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager:
        class: Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
