services:
    sidus_eav_model.finder:
        class: Sidus\EAVModelBundle\Doctrine\EAVFinder
        arguments:
            - '@doctrine'
            - '@sidus_eav_model.entity.data_loader'

    sidus_eav_model.integrity_constraint_manager:
        class: Sidus\EAVModelBundle\Doctrine\IntegrityConstraintManager
        arguments:
            - '@doctrine'
