parameters:
    sidus_eav_model.attribute.class: Sidus\EAVModelBundle\Model\Attribute
    sidus_eav_model.family.class: Sidus\EAVModelBundle\Model\Family

services:
    Sidus\EAVModelBundle\Doctrine\DataLoaderInterface:
        alias: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader

    Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader:
        class: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader
        arguments:
            - '@doctrine.orm.entity_manager'
