parameters:
    sidus_eav_model.attribute.class: Sidus\EAVModelBundle\Model\Attribute
    sidus_eav_model.family.class: Sidus\EAVModelBundle\Model\Family

services:
    sidus_eav_model.entity.data_loader:
        class: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader
        arguments:
            - '@doctrine.orm.entity_manager'
