parameters:
    sidus_eav_model.attribute.class: Sidus\EAVModelBundle\Model\Attribute
    sidus_eav_model.family.class: Sidus\EAVModelBundle\Model\Family

services:
    Sidus\EAVModelBundle\Doctrine\DataLoaderInterface:
        alias: Sidus\EAVModelBundle\Doctrine\ContextualizedOptimizedDataLoader

    Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader:
        class: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader
        arguments:
            - '@sidus_eav_model.entity_manager'

    Sidus\EAVModelBundle\Doctrine\ContextualizedDataLoaderInterface:
        alias: Sidus\EAVModelBundle\Doctrine\ContextualizedOptimizedDataLoader

    Sidus\EAVModelBundle\Doctrine\ContextualizedOptimizedDataLoader:
        class: Sidus\EAVModelBundle\Doctrine\ContextualizedOptimizedDataLoader
        parent: Sidus\EAVModelBundle\Doctrine\OptimizedDataLoader
