services:
    sidus_eav_model.doctrine.metadata.mapper:
        class: Sidus\EAVModelBundle\Event\DoctrineMetadataListener
        arguments:
            - '%sidus_eav_model.entity.data.class%'
            - '%sidus_eav_model.entity.value.class%'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
