services:
    Sidus\EAVModelBundle\Manager\DataManager:
        class: Sidus\EAVModelBundle\Manager\DataManager
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '%sidus_eav_model.entity.data.class%'
