# WARNING : Symfony's serializer has to be enabled in configuration in order to work

parameters:
    sidus_eav_model.normalizer.data.ignored_attributes:
        - refererValues
        - refererDatas
        - currentContext
        - values
        - valueData
        - valuesData
        - value
        - familyCode
        - empty

    sidus_eav_model.normalizer.data.reference_attributes:
        - id
        - identifier
        - familyCode
        - label

    sidus_eav_model.normalizer.family.ignored_attributes:
        - matchingCodes
        - valueClass
        - context
        # pass children and parent families by references ?
        - parent
        - children

    sidus_eav_model.normalizer.attribute.ignored_attributes:
        - family # Prevent circular reference

services:
    sidus_eav_model.normalizer.data:
        parent: serializer.normalizer.object
        class: Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer
        arguments:
            - '@sidus_eav_model.serializer.handler.max_depth'
            - '@sidus_eav_model.serializer.handler.circular_reference'
            - '@sidus_eav_model.serializer.handler.by_reference'
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.data.ignored_attributes%']]
            - [setReferenceAttributes, ['%sidus_eav_model.normalizer.data.reference_attributes%']]
        tags:
            - { name: serializer.normalizer }

    sidus_eav_model.normalizer.generic:
        abstract: true
        parent: serializer.normalizer.object
        arguments:
            - '@sidus_eav_model.serializer.handler.max_depth'
            - '@sidus_eav_model.serializer.handler.by_reference'

    sidus_eav_model.normalizer.family:
        parent: sidus_eav_model.normalizer.generic
        class: Sidus\EAVModelBundle\Serializer\Normalizer\FamilyNormalizer
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.family.ignored_attributes%']]
        tags:
            - { name: serializer.normalizer }

    sidus_eav_model.normalizer.attribute:
        parent: sidus_eav_model.normalizer.generic
        class: Sidus\EAVModelBundle\Serializer\Normalizer\AttributeNormalizer
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.attribute.ignored_attributes%']]
        tags:
            - { name: serializer.normalizer }

    # Normalizer variants for flat formats
    sidus_eav_model.normalizer.data.flat:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer
        arguments:
            - '@sidus_eav_model.normalizer.data'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 1 }

    sidus_eav_model.normalizer.family.flat:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer
        arguments:
            - '@sidus_eav_model.normalizer.family'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 1 }

    sidus_eav_model.normalizer.attribute.flat:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer
        arguments:
            - '@sidus_eav_model.normalizer.attribute'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 1 }
