# WARNING : Symfony's serializer has to be enabled in configuration in order to work

parameters:
    sidus_eav_model.normalizer.data.ignored_attributes:
        - refererValues
        - refererDatas
        - currentContext
        - values
        - valueData
        - valuesData
        - value
        - familyCode
        - empty

    sidus_eav_model.normalizer.data.reference_attributes:
        - id
        - identifier
        - familyCode
        - label

    sidus_eav_model.normalizer.family.ignored_attributes:
        - matchingCodes
        - valueClass
        - context
        # pass children and parent families by references ?
        - parent
        - children

    sidus_eav_model.normalizer.attribute.ignored_attributes:
        - family # Prevent circular reference

services:
    Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer
        parent: serializer.normalizer.object
        arguments:
            - '@Sidus\EAVModelBundle\Serializer\MaxDepthHandler'
            - '@Sidus\EAVModelBundle\Serializer\CircularReferenceHandler'
            - '@Sidus\EAVModelBundle\Serializer\ByReferenceHandler'
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.data.ignored_attributes%']]
            - [setReferenceAttributes, ['%sidus_eav_model.normalizer.data.reference_attributes%']]
        tags:
            - { name: serializer.normalizer }

    sidus_eav_model.normalizer.generic:
        abstract: true
        parent: serializer.normalizer.object
        arguments:
            - '@Sidus\EAVModelBundle\Serializer\MaxDepthHandler'
            - '@Sidus\EAVModelBundle\Serializer\ByReferenceHandler'

    Sidus\EAVModelBundle\Serializer\Normalizer\FamilyNormalizer:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\FamilyNormalizer
        parent: sidus_eav_model.normalizer.generic
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.family.ignored_attributes%']]
        tags:
            - { name: serializer.normalizer }

    Sidus\EAVModelBundle\Serializer\Normalizer\AttributeNormalizer:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\AttributeNormalizer
        parent: sidus_eav_model.normalizer.generic
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.attribute.ignored_attributes%']]
        tags:
            - { name: serializer.normalizer }

    # Normalizer variants for flat formats
    sidus_eav_model.normalizer.data.flat:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer
        arguments:
            - '@Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 1 }

    sidus_eav_model.normalizer.family.flat:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer
        arguments:
            - '@Sidus\EAVModelBundle\Serializer\Normalizer\FamilyNormalizer'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 1 }

    sidus_eav_model.normalizer.attribute.flat:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer
        arguments:
            - '@Sidus\EAVModelBundle\Serializer\Normalizer\AttributeNormalizer'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 1 }
