services:
    Sidus\EAVModelBundle\Request\ParamConverter\DataParamConverter:
        class: Sidus\EAVModelBundle\Request\ParamConverter\DataParamConverter
        public: false
        arguments:
            - '%sidus_eav_model.entity.data.class%'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@Sidus\EAVModelBundle\Doctrine\DataLoaderInterface'
        tags:
            - { name: request.param_converter }

    Sidus\EAVModelBundle\Request\ParamConverter\FamilyParamConverter:
        class: Sidus\EAVModelBundle\Request\ParamConverter\FamilyParamConverter
        public: false
        arguments: ['@Sidus\EAVModelBundle\Registry\FamilyRegistry']
        tags:
            - { name: request.param_converter }

    Sidus\EAVModelBundle\Request\ParamConverter\AttributeParamConverter:
        class: Sidus\EAVModelBundle\Request\ParamConverter\AttributeParamConverter
        public: false
        arguments: ['@Sidus\EAVModelBundle\Registry\AttributeRegistry']
        tags:
            - { name: request.param_converter }
