services:
    Sidus\EAVModelBundle\Twig\SidusTwigExtension:
        class: Sidus\EAVModelBundle\Twig\SidusTwigExtension
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@translator'
        tags:
            - { name: twig.extension }

