services:
    Sidus\EAVModelBundle\Validator\Constraints\DataValidator:
        class: Sidus\EAVModelBundle\Validator\Constraints\DataValidator
        public: false
        arguments:
            - '%sidus_eav_model.entity.data.class%'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@Symfony\Component\Translation\TranslatorInterface'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '@Psr\Log\LoggerInterface'
        tags:
            - { name: validator.constraint_validator }
